name: cf_xarray
channels:
  - conda-forge
dependencies:
  - matplotlib
  - netcdf4
  - pip
  - xarray
  - pooch
  - xesmf
  - intake-xarray
  - intake-esm
  - gcsfs
  - nc-time-axis
  - pip:
    - git+https://github.com/xarray-contrib/cf-xarray
