name: cf_xarray_earthcube
channels:
  - conda-forge
dependencies:
  - matplotlib=3.4.2
  - netcdf4=1.5.6
  - xarray=0.18.0
  - pooch=1.3.0
  - xesmf=0.5.3
  - intake-xarray=0.5.0
  - intake-esm=2021.1.15
  - gcsfs==2021.4.0
  - nc-time-axis=1.2.0
  - cf_xarray=0.5.2
  - jupyter_contrib_nbextensions=0.5.1
